CREATE TYPE "public"."cvi_member_type" AS ENUM('chord', 'brace');--> statement-breakpoint
CREATE TYPE "public"."fmd_attempt" AS ENUM('dry', 'flooded', 'na');--> statement-breakpoint
CREATE TYPE "public"."gvi_condition" AS ENUM('ok', 'not_ok');--> statement-breakpoint
CREATE TYPE "public"."inspection_type" AS ENUM('GVI', 'CVI', 'MGI', 'CP', 'FMD', 'SCOUR');--> statement-breakpoint
CREATE TYPE "public"."item_status" AS ENUM('not_set', 'pending', 'complete');--> statement-breakpoint
CREATE TYPE "public"."mgi_criteria_preset" AS ENUM('project_default', 'client_cnc', 'manual');--> statement-breakpoint
CREATE TYPE "public"."mgi_growth_type" AS ENUM('soft', 'hard');--> statement-breakpoint
CREATE TYPE "public"."recording_status" AS ENUM('recording', 'finalized', 'interrupted', 'finalization_failed', 'canceled');--> statement-breakpoint
CREATE TYPE "public"."scour_exposed_pile" AS ENUM('exposed', 'not_exposed');--> statement-breakpoint
CREATE TABLE "asset" (
	"asset_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "asset_asset_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"name" text NOT NULL,
	"asset_type" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "component" (
	"component_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "component_component_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"asset_id" integer NOT NULL,
	"project_id" integer NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "item" (
	"item_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "item_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"component_id" integer NOT NULL,
	"project_id" integer NOT NULL,
	"asset_id" integer NOT NULL,
	"item_label" text NOT NULL,
	"position" text,
	"status" "item_status" DEFAULT 'not_set' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone,
	CONSTRAINT "item_label_within_component" UNIQUE("component_id","item_label")
);
--> statement-breakpoint
CREATE TABLE "master_video" (
	"master_video_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "master_video_master_video_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"session_id" integer NOT NULL,
	"file_url" text NOT NULL,
	"thumbnail_url" text,
	"start_epoch" integer NOT NULL,
	"end_epoch" integer,
	"recording_status" "recording_status" DEFAULT 'finalized' NOT NULL,
	"source_kind" text,
	"input_id" text,
	"source_index" integer DEFAULT 1 NOT NULL,
	"is_primary" boolean DEFAULT false NOT NULL,
	"source_name" text,
	"started_at" timestamp with time zone,
	"stopped_at" timestamp with time zone,
	"duration_ms" integer,
	"file_size" integer,
	"recovery_status" text,
	"finalization_error" text,
	"last_updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "organization" (
	"organization_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "organization_organization_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "organization_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "project" (
	"project_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "project_project_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"description" text,
	"document_id" text,
	"organization_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "result" (
	"result_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "result_result_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"session_item_id" integer NOT NULL,
	"inspection_type_code" "inspection_type" NOT NULL,
	"project_id" integer NOT NULL,
	"asset_id" integer NOT NULL,
	"component_id" integer NOT NULL,
	"item_id" integer NOT NULL,
	"session_id" integer NOT NULL,
	"remarks" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "result_cp" (
	"result_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "result_cp_result_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"anodeType" text,
	"voltage_mv" integer,
	"depletion" text,
	"anodeWidth" integer,
	"anodeHeight" integer,
	"anodeLength" integer,
	"widestPit" integer,
	"deepestPit" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "result_cvi" (
	"result_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "result_cvi_result_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"datum_reference" text,
	"member_type" "cvi_member_type" NOT NULL,
	"cp_potential_mv" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "result_cvi_position" (
	"position_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "result_cvi_position_position_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"result_id" integer NOT NULL,
	"clock_position" text NOT NULL,
	"ut_mm" double precision,
	"findings" text,
	"sort_order" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "result_fmd" (
	"result_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "result_fmd_result_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"depth_el" double precision,
	"initialAttempt" "fmd_attempt" NOT NULL,
	"additionalAttempt1" "fmd_attempt" NOT NULL,
	"additionalAttempt2" "fmd_attempt" NOT NULL,
	"additionalAttempt3" "fmd_attempt" NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "result_gvi" (
	"result_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "result_gvi_result_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"gvi_cp" integer,
	"gvi_ut" integer,
	"condition" "gvi_condition" NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "result_image" (
	"image_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "result_image_image_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"result_id" integer NOT NULL,
	"raw_url" text NOT NULL,
	"annotated_url" text,
	"remarks" text
);
--> statement-breakpoint
CREATE TABLE "result_mgi" (
	"result_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "result_mgi_result_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"no_mg_observed" integer DEFAULT 0 NOT NULL,
	"criteria_preset" "mgi_criteria_preset",
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "result_mgi_no_mg_observed_check" CHECK ("result_mgi"."no_mg_observed" IN (0, 1))
);
--> statement-breakpoint
CREATE TABLE "result_mgi_finding" (
	"finding_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "result_mgi_finding_finding_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"result_mgi_id" integer NOT NULL,
	"growth_type" "mgi_growth_type",
	"species" text NOT NULL,
	"species_other_text" text,
	"coverage_percent" integer,
	"thickness_mm" integer,
	"remarks" text,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "result_scour" (
	"result_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "result_scour_result_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"exposed_pile" "scour_exposed_pile" NOT NULL,
	"exposed_pile_height" double precision,
	"height_leg1" double precision,
	"height_midpoint" double precision,
	"height_leg2" double precision,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "session" (
	"session_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "session_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"name" text,
	"started_at" timestamp with time zone,
	"ended_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "session_item" (
	"session_item_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "session_item_session_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"session_id" integer NOT NULL,
	"item_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "session_item_session_id_item_id_unique" UNIQUE("session_id","item_id")
);
--> statement-breakpoint
CREATE TABLE "timeline_thumbnail" (
	"thumbnail_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "timeline_thumbnail_thumbnail_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"master_video_id" integer NOT NULL,
	"timestamp_ms" integer NOT NULL,
	"image_path" text NOT NULL,
	"width" integer NOT NULL,
	"height" integer NOT NULL,
	"size_bytes" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "video_clip" (
	"clip_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "video_clip_clip_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"result_id" integer NOT NULL,
	"master_video_id" integer NOT NULL,
	"start_offset_ms" integer NOT NULL,
	"end_offset_ms" integer,
	"clip_file_url" text,
	"thumbnail_url" text,
	"recording_status" "recording_status" DEFAULT 'finalized' NOT NULL,
	"recording_started_at" timestamp with time zone,
	"recording_stopped_at" timestamp with time zone,
	"file_size" integer,
	"recovery_status" text,
	"finalization_error" text,
	"last_updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "asset" ADD CONSTRAINT "asset_project_id_project_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."project"("project_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "component" ADD CONSTRAINT "component_asset_id_asset_asset_id_fk" FOREIGN KEY ("asset_id") REFERENCES "public"."asset"("asset_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "item" ADD CONSTRAINT "item_component_id_component_component_id_fk" FOREIGN KEY ("component_id") REFERENCES "public"."component"("component_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "master_video" ADD CONSTRAINT "master_video_session_id_session_session_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."session"("session_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project" ADD CONSTRAINT "project_organization_id_organization_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("organization_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_session_item_id_session_item_session_item_id_fk" FOREIGN KEY ("session_item_id") REFERENCES "public"."session_item"("session_item_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_cp" ADD CONSTRAINT "result_cp_result_id_result_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_cvi" ADD CONSTRAINT "result_cvi_result_id_result_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_cvi_position" ADD CONSTRAINT "result_cvi_position_result_id_result_cvi_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result_cvi"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_fmd" ADD CONSTRAINT "result_fmd_result_id_result_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_gvi" ADD CONSTRAINT "result_gvi_result_id_result_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_image" ADD CONSTRAINT "result_image_result_id_result_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_mgi" ADD CONSTRAINT "result_mgi_result_id_result_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_mgi_finding" ADD CONSTRAINT "result_mgi_finding_result_mgi_id_result_mgi_result_id_fk" FOREIGN KEY ("result_mgi_id") REFERENCES "public"."result_mgi"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_scour" ADD CONSTRAINT "result_scour_result_id_result_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_project_id_project_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."project"("project_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_item" ADD CONSTRAINT "session_item_session_id_session_session_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."session"("session_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_item" ADD CONSTRAINT "session_item_item_id_item_item_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."item"("item_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "timeline_thumbnail" ADD CONSTRAINT "timeline_thumbnail_master_video_id_master_video_master_video_id_fk" FOREIGN KEY ("master_video_id") REFERENCES "public"."master_video"("master_video_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "video_clip" ADD CONSTRAINT "video_clip_result_id_result_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "video_clip" ADD CONSTRAINT "video_clip_master_video_id_master_video_master_video_id_fk" FOREIGN KEY ("master_video_id") REFERENCES "public"."master_video"("master_video_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_asset_project_id" ON "asset" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "idx_component_asset_id" ON "component" USING btree ("asset_id");--> statement-breakpoint
CREATE INDEX "idx_component_project_id" ON "component" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "idx_item_component_id" ON "item" USING btree ("component_id");--> statement-breakpoint
CREATE INDEX "idx_item_project_id" ON "item" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "idx_item_asset_id" ON "item" USING btree ("asset_id");--> statement-breakpoint
CREATE INDEX "idx_project_title" ON "project" USING btree ("title");--> statement-breakpoint
CREATE INDEX "idx_result_session_item_id" ON "result" USING btree ("session_item_id");--> statement-breakpoint
CREATE INDEX "idx_result_project_id" ON "result" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "idx_result_asset_id" ON "result" USING btree ("asset_id");--> statement-breakpoint
CREATE INDEX "idx_result_component_id" ON "result" USING btree ("component_id");--> statement-breakpoint
CREATE INDEX "idx_result_item_id" ON "result" USING btree ("item_id");--> statement-breakpoint
CREATE INDEX "idx_result_session_id" ON "result" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "idx_result_inspection_type_code" ON "result" USING btree ("inspection_type_code");--> statement-breakpoint
CREATE INDEX "idx_result_cvi_position_result_id" ON "result_cvi_position" USING btree ("result_id");--> statement-breakpoint
CREATE INDEX "idx_result_mgi_finding_mgi" ON "result_mgi_finding" USING btree ("result_mgi_id");--> statement-breakpoint
CREATE INDEX "idx_session_project_id" ON "session" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "idx_session_item_session_id" ON "session_item" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "idx_session_item_item_id" ON "session_item" USING btree ("item_id");