CREATE TYPE "public"."bsi_alignment_condition" AS ENUM('aligned', 'misaligned');--> statement-breakpoint
CREATE TYPE "public"."bsi_gap_condition" AS ENUM('gap', 'no_gap');--> statement-breakpoint
CREATE TYPE "public"."bsi_misaligned_position" AS ENUM('top', 'mid', 'bottom');--> statement-breakpoint
CREATE TYPE "public"."cvi_member_type" AS ENUM('chord', 'brace');--> statement-breakpoint
CREATE TYPE "public"."fmd_attempt" AS ENUM('dry', 'flooded', 'na');--> statement-breakpoint
CREATE TYPE "public"."gvi_condition" AS ENUM('ok', 'not_ok');--> statement-breakpoint
CREATE TYPE "public"."inspection_type" AS ENUM('GVI', 'CVI', 'MGI', 'CP', 'FMD', 'SCOUR', 'BSI');--> statement-breakpoint
CREATE TYPE "public"."mgi_criteria_preset" AS ENUM('project_default', 'client_cnc', 'manual');--> statement-breakpoint
CREATE TYPE "public"."mgi_growth_type" AS ENUM('soft', 'hard');--> statement-breakpoint
CREATE TYPE "public"."recording_ingest_kind" AS ENUM('master', 'clip');--> statement-breakpoint
CREATE TYPE "public"."scour_exposed_pile" AS ENUM('exposed', 'not_exposed');--> statement-breakpoint
CREATE TABLE "description" (
	"description_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "description_description_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"task_code_id" integer NOT NULL,
	"label" text NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "inspection_form" (
	"inspection_form_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "inspection_form_inspection_form_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"inspection_type_code" "inspection_type" NOT NULL,
	"version" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "inspection_form_field" (
	"inspection_form_field_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "inspection_form_field_inspection_form_field_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"inspection_form_id" integer NOT NULL,
	"label" text NOT NULL,
	"data_type" text NOT NULL,
	"required" boolean DEFAULT false NOT NULL,
	"is_builtin" boolean DEFAULT false NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "inspection_form_field_data_type_check" CHECK ("inspection_form_field"."data_type" IN ('integer', 'decimal', 'text', 'boolean'))
);
--> statement-breakpoint
CREATE TABLE "organization" (
	"organization_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "organization_organization_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "organization_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "part_code" (
	"part_code_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "part_code_part_code_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type_id" integer NOT NULL,
	"code" text NOT NULL,
	"label" text,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "project" (
	"project_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "project_project_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"description" text,
	"document_id" text,
	"organization_id" integer,
	"display_number" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "recording_ingest" (
	"ingest_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "recording_ingest_ingest_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"kind" "recording_ingest_kind" NOT NULL,
	"session_id" integer,
	"clip_id" integer,
	"ticket_hash" text NOT NULL,
	"key_date" date NOT NULL,
	"key_prefix" text NOT NULL,
	"opened_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_segment_at" timestamp with time zone,
	"closed_at" timestamp with time zone,
	"contiguous_sequence" integer DEFAULT -1 NOT NULL,
	"final_sequence" integer,
	"duration_ms" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "recording_ingest_kind_target_check" CHECK (("recording_ingest"."kind" = 'master' AND "recording_ingest"."session_id" IS NOT NULL AND "recording_ingest"."clip_id" IS NULL)
       OR ("recording_ingest"."kind" = 'clip' AND "recording_ingest"."clip_id" IS NOT NULL AND "recording_ingest"."session_id" IS NULL))
);
--> statement-breakpoint
CREATE TABLE "recording_ingest_segment" (
	"ingest_id" integer NOT NULL,
	"sequence" integer NOT NULL,
	"checksum_sha256" text NOT NULL,
	"size_bytes" bigint NOT NULL,
	"duration_ms" integer NOT NULL,
	"discontinuity" boolean DEFAULT false NOT NULL,
	"object_key" text NOT NULL,
	"stored_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "recording_ingest_segment_ingest_id_sequence_pk" PRIMARY KEY("ingest_id","sequence")
);
--> statement-breakpoint
CREATE TABLE "result" (
	"result_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "result_result_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"inspection_type_code" "inspection_type" NOT NULL,
	"project_id" integer NOT NULL,
	"session_id" integer NOT NULL,
	"description_id" integer,
	"part_code_id" integer,
	"master_start_ms" bigint,
	"master_end_ms" bigint,
	"layer" integer,
	"custom_values" jsonb,
	"inspection_form_id" integer,
	"display_number" integer NOT NULL,
	"remarks" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone,
	CONSTRAINT "result_target_check" CHECK (num_nonnulls("result"."description_id", "result"."part_code_id") = 1),
	CONSTRAINT "result_layer_check" CHECK ("result"."layer" IS NULL OR "result"."layer" BETWEEN 1 AND 2)
);
--> statement-breakpoint
CREATE TABLE "result_bsi" (
	"result_id" integer PRIMARY KEY NOT NULL,
	"clamp_type" text,
	"depth_el" double precision,
	"clamp_bolt_nut_quantity" integer,
	"outboard_clamp_cp" double precision,
	"cp_anomaly_recommendation" text,
	"hinge_pin" boolean,
	"hinge_bolt_nut_quantity" integer,
	"liners" boolean,
	"inboard_gap_condition" "bsi_gap_condition" NOT NULL,
	"inboard_estimate_gap" double precision,
	"inboard_alignment_condition" "bsi_alignment_condition" NOT NULL,
	"inboard_misaligned_position" "bsi_misaligned_position",
	"inboard_anomaly_recommendation" text,
	"outboard_gap_condition" "bsi_gap_condition" NOT NULL,
	"outboard_estimate_gap" double precision,
	"outboard_alignment_condition" "bsi_alignment_condition" NOT NULL,
	"outboard_misaligned_position" "bsi_misaligned_position",
	"outboard_anomaly_recommendation" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "result_bsi_clamp_missing_bolt" (
	"missing_bolt_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "result_bsi_clamp_missing_bolt_missing_bolt_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"result_id" integer NOT NULL,
	"position" text NOT NULL,
	"sort_order" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "result_bsi_clamp_missing_washer" (
	"missing_washer_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "result_bsi_clamp_missing_washer_missing_washer_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"result_id" integer NOT NULL,
	"position" text NOT NULL,
	"sort_order" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "result_bsi_hinge_missing_bolt" (
	"missing_bolt_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "result_bsi_hinge_missing_bolt_missing_bolt_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"result_id" integer NOT NULL,
	"position" text NOT NULL,
	"sort_order" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "result_bsi_hinge_missing_washer" (
	"missing_washer_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "result_bsi_hinge_missing_washer_missing_washer_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"result_id" integer NOT NULL,
	"position" text NOT NULL,
	"sort_order" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "result_cp" (
	"result_id" integer PRIMARY KEY NOT NULL,
	"anodeType" text,
	"voltage_mv" integer,
	"depletion" text,
	"anodeWidth" integer,
	"anodeHeight" integer,
	"anodeLength" integer,
	"widestPit" integer,
	"deepestPit" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "result_cvi" (
	"result_id" integer PRIMARY KEY NOT NULL,
	"datum_reference" text,
	"member_type" "cvi_member_type" NOT NULL,
	"cp_potential_mv" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "result_cvi_position" (
	"position_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "result_cvi_position_position_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"result_id" integer NOT NULL,
	"clock_position" text NOT NULL,
	"ut_mm" double precision,
	"findings" text,
	"sort_order" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "result_fmd" (
	"result_id" integer PRIMARY KEY NOT NULL,
	"depth_el" double precision,
	"initialAttempt" "fmd_attempt" NOT NULL,
	"additionalAttempt1" "fmd_attempt" NOT NULL,
	"additionalAttempt2" "fmd_attempt" NOT NULL,
	"additionalAttempt3" "fmd_attempt" NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "result_gvi" (
	"result_id" integer PRIMARY KEY NOT NULL,
	"kp_range" text,
	"depth_el" double precision,
	"gvi_cp" integer,
	"gvi_ut" integer,
	"condition" "gvi_condition" NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "result_image" (
	"image_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "result_image_image_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"result_id" integer NOT NULL,
	"storage_stem" text NOT NULL,
	"content_type" text DEFAULT 'image/png' NOT NULL,
	"has_annotated" boolean DEFAULT false NOT NULL,
	"remarks" text
);
--> statement-breakpoint
CREATE TABLE "result_mgi" (
	"result_id" integer PRIMARY KEY NOT NULL,
	"no_mg_observed" integer DEFAULT 0 NOT NULL,
	"criteria_preset" "mgi_criteria_preset",
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "result_mgi_no_mg_observed_check" CHECK ("result_mgi"."no_mg_observed" IN (0, 1))
);
--> statement-breakpoint
CREATE TABLE "result_mgi_finding" (
	"finding_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "result_mgi_finding_finding_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"result_mgi_id" integer NOT NULL,
	"growth_type" "mgi_growth_type",
	"species" text NOT NULL,
	"species_other_text" text,
	"coverage_percent" integer,
	"thickness_mm" integer,
	"remarks" text,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "result_scour" (
	"result_id" integer PRIMARY KEY NOT NULL,
	"exposed_pile" "scour_exposed_pile" NOT NULL,
	"exposed_pile_height" double precision,
	"height_leg1" double precision,
	"height_midpoint" double precision,
	"height_leg2" double precision,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "session" (
	"session_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "session_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"name" text,
	"display_number" integer NOT NULL,
	"started_at" timestamp with time zone,
	"ended_at" timestamp with time zone,
	"start_epoch" bigint,
	"end_epoch" bigint,
	"duration_ms" integer,
	"recording_updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "task_code" (
	"task_code_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "task_code_task_code_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"task_group_id" integer NOT NULL,
	"code" text NOT NULL,
	"label" text NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "task_group" (
	"task_group_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "task_group_task_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"code" text NOT NULL,
	"label" text NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "timeline_thumbnail" (
	"thumbnail_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "timeline_thumbnail_thumbnail_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"session_id" integer NOT NULL,
	"timestamp_ms" integer NOT NULL,
	"storage_stem" text NOT NULL,
	"width" integer NOT NULL,
	"height" integer NOT NULL,
	"size_bytes" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "type" (
	"type_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "type_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"description_id" integer NOT NULL,
	"code" text NOT NULL,
	"label" text NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "video_clip" (
	"clip_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "video_clip_clip_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"result_id" integer NOT NULL,
	"session_id" integer NOT NULL,
	"start_offset_ms" integer NOT NULL,
	"end_offset_ms" integer,
	"thumbnail_key" text,
	"last_updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "description" ADD CONSTRAINT "description_task_code_id_task_code_task_code_id_fk" FOREIGN KEY ("task_code_id") REFERENCES "public"."task_code"("task_code_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inspection_form" ADD CONSTRAINT "inspection_form_project_id_project_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."project"("project_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inspection_form_field" ADD CONSTRAINT "inspection_form_field_inspection_form_id_inspection_form_inspection_form_id_fk" FOREIGN KEY ("inspection_form_id") REFERENCES "public"."inspection_form"("inspection_form_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "part_code" ADD CONSTRAINT "part_code_type_id_type_type_id_fk" FOREIGN KEY ("type_id") REFERENCES "public"."type"("type_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project" ADD CONSTRAINT "project_organization_id_organization_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("organization_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recording_ingest" ADD CONSTRAINT "recording_ingest_session_id_session_session_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."session"("session_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recording_ingest" ADD CONSTRAINT "recording_ingest_clip_id_video_clip_clip_id_fk" FOREIGN KEY ("clip_id") REFERENCES "public"."video_clip"("clip_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recording_ingest_segment" ADD CONSTRAINT "recording_ingest_segment_ingest_id_recording_ingest_ingest_id_fk" FOREIGN KEY ("ingest_id") REFERENCES "public"."recording_ingest"("ingest_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_description_id_description_description_id_fk" FOREIGN KEY ("description_id") REFERENCES "public"."description"("description_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_part_code_id_part_code_part_code_id_fk" FOREIGN KEY ("part_code_id") REFERENCES "public"."part_code"("part_code_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_inspection_form_id_inspection_form_inspection_form_id_fk" FOREIGN KEY ("inspection_form_id") REFERENCES "public"."inspection_form"("inspection_form_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_bsi" ADD CONSTRAINT "result_bsi_result_id_result_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_bsi_clamp_missing_bolt" ADD CONSTRAINT "result_bsi_clamp_missing_bolt_result_id_result_bsi_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result_bsi"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_bsi_clamp_missing_washer" ADD CONSTRAINT "result_bsi_clamp_missing_washer_result_id_result_bsi_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result_bsi"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_bsi_hinge_missing_bolt" ADD CONSTRAINT "result_bsi_hinge_missing_bolt_result_id_result_bsi_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result_bsi"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_bsi_hinge_missing_washer" ADD CONSTRAINT "result_bsi_hinge_missing_washer_result_id_result_bsi_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result_bsi"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_cp" ADD CONSTRAINT "result_cp_result_id_result_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_cvi" ADD CONSTRAINT "result_cvi_result_id_result_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_cvi_position" ADD CONSTRAINT "result_cvi_position_result_id_result_cvi_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result_cvi"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_fmd" ADD CONSTRAINT "result_fmd_result_id_result_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_gvi" ADD CONSTRAINT "result_gvi_result_id_result_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_image" ADD CONSTRAINT "result_image_result_id_result_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_mgi" ADD CONSTRAINT "result_mgi_result_id_result_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_mgi_finding" ADD CONSTRAINT "result_mgi_finding_result_mgi_id_result_mgi_result_id_fk" FOREIGN KEY ("result_mgi_id") REFERENCES "public"."result_mgi"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_scour" ADD CONSTRAINT "result_scour_result_id_result_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_project_id_project_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."project"("project_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_code" ADD CONSTRAINT "task_code_task_group_id_task_group_task_group_id_fk" FOREIGN KEY ("task_group_id") REFERENCES "public"."task_group"("task_group_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_group" ADD CONSTRAINT "task_group_project_id_project_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."project"("project_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "timeline_thumbnail" ADD CONSTRAINT "timeline_thumbnail_session_id_session_session_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."session"("session_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "type" ADD CONSTRAINT "type_description_id_description_description_id_fk" FOREIGN KEY ("description_id") REFERENCES "public"."description"("description_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "video_clip" ADD CONSTRAINT "video_clip_result_id_result_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "video_clip" ADD CONSTRAINT "video_clip_session_id_session_session_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."session"("session_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_description_task_code_id" ON "description" USING btree ("task_code_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_description_task_code_label" ON "description" USING btree ("task_code_id","label");--> statement-breakpoint
CREATE INDEX "idx_inspection_form_project_id" ON "inspection_form" USING btree ("project_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_inspection_form_project_type_version" ON "inspection_form" USING btree ("project_id","inspection_type_code","version");--> statement-breakpoint
CREATE INDEX "idx_inspection_form_field_form_id" ON "inspection_form_field" USING btree ("inspection_form_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_inspection_form_field_label" ON "inspection_form_field" USING btree ("inspection_form_id","label");--> statement-breakpoint
CREATE INDEX "idx_part_code_type_id" ON "part_code" USING btree ("type_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_part_code_type_code" ON "part_code" USING btree ("type_id","code");--> statement-breakpoint
CREATE INDEX "idx_project_title" ON "project" USING btree ("title");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_project_display_org" ON "project" USING btree ("organization_id","display_number") WHERE "project"."organization_id" IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_project_display_noorg" ON "project" USING btree ("display_number") WHERE "project"."organization_id" IS NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_recording_ingest_open_clip" ON "recording_ingest" USING btree ("clip_id") WHERE "recording_ingest"."closed_at" IS NULL AND "recording_ingest"."kind" = 'clip';--> statement-breakpoint
CREATE UNIQUE INDEX "uq_recording_ingest_open_session" ON "recording_ingest" USING btree ("session_id") WHERE "recording_ingest"."closed_at" IS NULL AND "recording_ingest"."kind" = 'master';--> statement-breakpoint
CREATE INDEX "idx_recording_ingest_open" ON "recording_ingest" USING btree ("closed_at");--> statement-breakpoint
CREATE INDEX "idx_result_project_id" ON "result" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "idx_result_session_id" ON "result" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "idx_result_description_id" ON "result" USING btree ("description_id");--> statement-breakpoint
CREATE INDEX "idx_result_part_code_id" ON "result" USING btree ("part_code_id");--> statement-breakpoint
CREATE INDEX "idx_result_session_layer" ON "result" USING btree ("session_id","layer");--> statement-breakpoint
CREATE INDEX "idx_result_inspection_type_code" ON "result" USING btree ("inspection_type_code");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_result_session_display" ON "result" USING btree ("session_id","display_number");--> statement-breakpoint
CREATE INDEX "idx_result_bsi_clamp_missing_bolt_result_id" ON "result_bsi_clamp_missing_bolt" USING btree ("result_id");--> statement-breakpoint
CREATE INDEX "idx_result_bsi_clamp_missing_washer_result_id" ON "result_bsi_clamp_missing_washer" USING btree ("result_id");--> statement-breakpoint
CREATE INDEX "idx_result_bsi_hinge_missing_bolt_result_id" ON "result_bsi_hinge_missing_bolt" USING btree ("result_id");--> statement-breakpoint
CREATE INDEX "idx_result_bsi_hinge_missing_washer_result_id" ON "result_bsi_hinge_missing_washer" USING btree ("result_id");--> statement-breakpoint
CREATE INDEX "idx_result_cvi_position_result_id" ON "result_cvi_position" USING btree ("result_id");--> statement-breakpoint
CREATE INDEX "idx_result_image_result_id" ON "result_image" USING btree ("result_id");--> statement-breakpoint
CREATE INDEX "idx_result_mgi_finding_mgi" ON "result_mgi_finding" USING btree ("result_mgi_id");--> statement-breakpoint
CREATE INDEX "idx_session_project_id" ON "session" USING btree ("project_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uniq_session_project_display" ON "session" USING btree ("project_id","display_number");--> statement-breakpoint
CREATE INDEX "idx_task_code_task_group_id" ON "task_code" USING btree ("task_group_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_task_code_group_code" ON "task_code" USING btree ("task_group_id","code");--> statement-breakpoint
CREATE INDEX "idx_task_group_project_id" ON "task_group" USING btree ("project_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_task_group_project_code" ON "task_group" USING btree ("project_id","code");--> statement-breakpoint
CREATE INDEX "idx_timeline_thumbnail_session_ts" ON "timeline_thumbnail" USING btree ("session_id","timestamp_ms");--> statement-breakpoint
CREATE INDEX "idx_type_description_id" ON "type" USING btree ("description_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_type_description_code" ON "type" USING btree ("description_id","code");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_video_clip_result_id" ON "video_clip" USING btree ("result_id");--> statement-breakpoint
CREATE INDEX "idx_video_clip_session_id" ON "video_clip" USING btree ("session_id");