CREATE TABLE "planned_inspection" (
	"planned_inspection_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "planned_inspection_planned_inspection_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"description_id" integer,
	"part_code_id" integer,
	"inspection_type_code" "inspection_type" NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uq_planned_inspection_target" UNIQUE NULLS NOT DISTINCT("project_id","description_id","part_code_id","inspection_type_code"),
	CONSTRAINT "planned_inspection_target_check" CHECK (num_nonnulls("planned_inspection"."description_id", "planned_inspection"."part_code_id") = 1)
);
--> statement-breakpoint
ALTER TABLE "planned_inspection" ADD CONSTRAINT "planned_inspection_project_id_project_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."project"("project_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "planned_inspection" ADD CONSTRAINT "planned_inspection_description_id_description_description_id_fk" FOREIGN KEY ("description_id") REFERENCES "public"."description"("description_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "planned_inspection" ADD CONSTRAINT "planned_inspection_part_code_id_part_code_part_code_id_fk" FOREIGN KEY ("part_code_id") REFERENCES "public"."part_code"("part_code_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_planned_inspection_project_id" ON "planned_inspection" USING btree ("project_id");