ALTER TYPE "public"."inspection_type" ADD VALUE 'CAISSON' BEFORE 'RA';--> statement-breakpoint
CREATE TABLE "result_dvi" (
	"result_id" integer PRIMARY KEY NOT NULL,
	"datum_reference" text,
	"member_type" "cvi_member_type" NOT NULL,
	"cp_potential_mv" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "result_dvi_position" (
	"position_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "result_dvi_position_position_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"result_id" integer NOT NULL,
	"clock_position" text NOT NULL,
	"ut_mm" double precision,
	"findings" text,
	"sort_order" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "result_dvi" ADD CONSTRAINT "result_dvi_result_id_result_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_dvi_position" ADD CONSTRAINT "result_dvi_position_result_id_result_cvi_result_id_fk" FOREIGN KEY ("result_id") REFERENCES "public"."result_cvi"("result_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_result_dvi_position_result_id" ON "result_dvi_position" USING btree ("result_id");