CREATE TYPE "public"."recording_ingest_kind" AS ENUM('master', 'clip');--> statement-breakpoint
CREATE TABLE "recording_ingest" (
	"ingest_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "recording_ingest_ingest_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"kind" "recording_ingest_kind" NOT NULL,
	"master_video_id" integer,
	"clip_id" integer,
	"ticket_hash" text NOT NULL,
	"key_date" date NOT NULL,
	"opened_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_segment_at" timestamp with time zone,
	"closed_at" timestamp with time zone,
	"contiguous_sequence" integer DEFAULT -1 NOT NULL,
	"final_sequence" integer,
	"duration_ms" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "recording_ingest_kind_target_check" CHECK (("recording_ingest"."kind" = 'master' AND "recording_ingest"."master_video_id" IS NOT NULL AND "recording_ingest"."clip_id" IS NULL)
       OR ("recording_ingest"."kind" = 'clip' AND "recording_ingest"."clip_id" IS NOT NULL AND "recording_ingest"."master_video_id" IS NULL))
);
--> statement-breakpoint
CREATE TABLE "recording_ingest_segment" (
	"ingest_id" integer NOT NULL,
	"sequence" integer NOT NULL,
	"checksum_sha256" text NOT NULL,
	"size_bytes" bigint NOT NULL,
	"duration_ms" integer NOT NULL,
	"discontinuity" boolean DEFAULT false NOT NULL,
	"object_key" text NOT NULL,
	"stored_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "recording_ingest_segment_ingest_id_sequence_pk" PRIMARY KEY("ingest_id","sequence")
);
--> statement-breakpoint
ALTER TABLE "recording_ingest" ADD CONSTRAINT "recording_ingest_master_video_id_master_video_master_video_id_fk" FOREIGN KEY ("master_video_id") REFERENCES "public"."master_video"("master_video_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recording_ingest" ADD CONSTRAINT "recording_ingest_clip_id_video_clip_clip_id_fk" FOREIGN KEY ("clip_id") REFERENCES "public"."video_clip"("clip_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recording_ingest_segment" ADD CONSTRAINT "recording_ingest_segment_ingest_id_recording_ingest_ingest_id_fk" FOREIGN KEY ("ingest_id") REFERENCES "public"."recording_ingest"("ingest_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_recording_ingest_open_clip" ON "recording_ingest" USING btree ("clip_id") WHERE "recording_ingest"."closed_at" IS NULL AND "recording_ingest"."kind" = 'clip';--> statement-breakpoint
CREATE INDEX "idx_recording_ingest_open" ON "recording_ingest" USING btree ("closed_at");