-- Inspection redesign: task tree, type catalog, versioned forms, v2 result targets.
-- Hand-written (agent-authored): additive only; legacy tables stay until 0016.
CREATE TABLE "task_group" (
	"task_group_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"project_id" integer NOT NULL REFERENCES "project"("project_id") ON DELETE cascade,
	"group_code" text NOT NULL,
	"label" text NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "idx_task_group_project_id" ON "task_group" USING btree ("project_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_task_group_project_code" ON "task_group" USING btree ("project_id","group_code");--> statement-breakpoint
CREATE TABLE "task_code" (
	"task_code_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"task_group_id" integer NOT NULL REFERENCES "task_group"("task_group_id") ON DELETE cascade,
	"code" text NOT NULL,
	"label" text NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "idx_task_code_task_group_id" ON "task_code" USING btree ("task_group_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_task_code_group_code" ON "task_code" USING btree ("task_group_id","code");--> statement-breakpoint
CREATE TABLE "main_component" (
	"main_component_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"task_code_id" integer NOT NULL REFERENCES "task_code"("task_code_id") ON DELETE cascade,
	"description" text NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "idx_main_component_task_code_id" ON "main_component" USING btree ("task_code_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_main_component_task_code_description" ON "main_component" USING btree ("task_code_id","description");--> statement-breakpoint
CREATE TABLE "component_type" (
	"component_type_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"project_id" integer NOT NULL REFERENCES "project"("project_id") ON DELETE cascade,
	"type_code" text NOT NULL,
	"label" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "idx_component_type_project_id" ON "component_type" USING btree ("project_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_component_type_project_code" ON "component_type" USING btree ("project_id","type_code");--> statement-breakpoint
CREATE TABLE "main_component_type" (
	"main_component_type_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"main_component_id" integer NOT NULL REFERENCES "main_component"("main_component_id") ON DELETE cascade,
	"component_type_id" integer NOT NULL REFERENCES "component_type"("component_type_id") ON DELETE restrict,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "idx_main_component_type_main_component_id" ON "main_component_type" USING btree ("main_component_id");--> statement-breakpoint
CREATE INDEX "idx_main_component_type_component_type_id" ON "main_component_type" USING btree ("component_type_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_main_component_type_pair" ON "main_component_type" USING btree ("main_component_id","component_type_id");--> statement-breakpoint
CREATE TABLE "component_code" (
	"component_code_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"main_component_type_id" integer NOT NULL REFERENCES "main_component_type"("main_component_type_id") ON DELETE cascade,
	"code" text NOT NULL,
	"label" text,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "idx_component_code_main_component_type_id" ON "component_code" USING btree ("main_component_type_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_component_code_branch_code" ON "component_code" USING btree ("main_component_type_id","code");--> statement-breakpoint
CREATE TABLE "inspection_form" (
	"inspection_form_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"project_id" integer NOT NULL REFERENCES "project"("project_id") ON DELETE cascade,
	"inspection_type_code" "inspection_type" NOT NULL,
	"version" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "idx_inspection_form_project_id" ON "inspection_form" USING btree ("project_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_inspection_form_project_type_version" ON "inspection_form" USING btree ("project_id","inspection_type_code","version");--> statement-breakpoint
CREATE TABLE "inspection_form_field" (
	"inspection_form_field_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"inspection_form_id" integer NOT NULL REFERENCES "inspection_form"("inspection_form_id") ON DELETE cascade,
	"label" text NOT NULL,
	"data_type" text NOT NULL,
	"required" boolean DEFAULT false NOT NULL,
	"is_builtin" boolean DEFAULT false NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "idx_inspection_form_field_form_id" ON "inspection_form_field" USING btree ("inspection_form_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_inspection_form_field_label" ON "inspection_form_field" USING btree ("inspection_form_id","label");--> statement-breakpoint
ALTER TABLE "inspection_form_field" ADD CONSTRAINT "inspection_form_field_data_type_check" CHECK ("data_type" IN ('integer', 'decimal', 'text', 'boolean'));--> statement-breakpoint
ALTER TABLE "result" ADD COLUMN "main_component_id" integer;--> statement-breakpoint
ALTER TABLE "result" ADD COLUMN "component_code_id" integer;--> statement-breakpoint
ALTER TABLE "result" ADD COLUMN "master_start_ms" bigint;--> statement-breakpoint
ALTER TABLE "result" ADD COLUMN "master_end_ms" bigint;--> statement-breakpoint
ALTER TABLE "result" ADD COLUMN "layer" integer;--> statement-breakpoint
ALTER TABLE "result" ADD COLUMN "custom_values" jsonb;--> statement-breakpoint
ALTER TABLE "result" ADD COLUMN "inspection_form_id" integer;--> statement-breakpoint
ALTER TABLE "result" ALTER COLUMN "session_item_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "result" ALTER COLUMN "asset_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "result" ALTER COLUMN "component_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "result" ALTER COLUMN "item_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_main_component_id_main_component_id_fk" FOREIGN KEY ("main_component_id") REFERENCES "main_component"("main_component_id") ON DELETE restrict;--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_component_code_id_component_code_id_fk" FOREIGN KEY ("component_code_id") REFERENCES "component_code"("component_code_id") ON DELETE restrict;--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_inspection_form_id_inspection_form_id_fk" FOREIGN KEY ("inspection_form_id") REFERENCES "inspection_form"("inspection_form_id") ON DELETE restrict;--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_target_check" CHECK (num_nonnulls("main_component_id", "component_code_id") = 1 OR (num_nonnulls("main_component_id", "component_code_id") = 0 AND "session_item_id" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_layer_check" CHECK ("layer" IS NULL OR "layer" BETWEEN 1 AND 3);--> statement-breakpoint
CREATE INDEX "idx_result_main_component_id" ON "result" USING btree ("main_component_id");--> statement-breakpoint
CREATE INDEX "idx_result_component_code_id" ON "result" USING btree ("component_code_id");--> statement-breakpoint
CREATE INDEX "idx_result_session_layer" ON "result" USING btree ("session_id","layer");
