CREATE TABLE "description" (
	"description_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "description_description_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"task_code_id" integer NOT NULL,
	"label" text NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "part_code" (
	"part_code_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "part_code_part_code_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type_id" integer NOT NULL,
	"code" text NOT NULL,
	"label" text,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "type" (
	"type_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "type_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"description_id" integer NOT NULL,
	"code" text NOT NULL,
	"label" text NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "component_code" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "component_type" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "main_component" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "main_component_type" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "master_video" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "component_code" CASCADE;--> statement-breakpoint
DROP TABLE "component_type" CASCADE;--> statement-breakpoint
DROP TABLE "main_component" CASCADE;--> statement-breakpoint
DROP TABLE "main_component_type" CASCADE;--> statement-breakpoint
DROP TABLE "master_video" CASCADE;--> statement-breakpoint
ALTER TABLE "recording_ingest" DROP CONSTRAINT "recording_ingest_kind_target_check";--> statement-breakpoint
ALTER TABLE "result" DROP CONSTRAINT "result_target_check";--> statement-breakpoint
ALTER TABLE "result" DROP CONSTRAINT "result_layer_check";--> statement-breakpoint
--> statement-breakpoint
--> statement-breakpoint
--> statement-breakpoint
--> statement-breakpoint
--> statement-breakpoint
DROP INDEX "idx_result_main_component_id";--> statement-breakpoint
DROP INDEX "idx_result_component_code_id";--> statement-breakpoint
DROP INDEX "idx_timeline_thumbnail_master_video_ts";--> statement-breakpoint
DROP INDEX "idx_video_clip_master_video_id";--> statement-breakpoint
DROP INDEX "uq_task_group_project_code";--> statement-breakpoint
ALTER TABLE "recording_ingest" ADD COLUMN "session_id" integer;--> statement-breakpoint
ALTER TABLE "result" ADD COLUMN "description_id" integer;--> statement-breakpoint
ALTER TABLE "result" ADD COLUMN "part_code_id" integer;--> statement-breakpoint
ALTER TABLE "session" ADD COLUMN "start_epoch" bigint;--> statement-breakpoint
ALTER TABLE "session" ADD COLUMN "end_epoch" bigint;--> statement-breakpoint
ALTER TABLE "session" ADD COLUMN "duration_ms" integer;--> statement-breakpoint
ALTER TABLE "session" ADD COLUMN "recording_updated_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "task_group" ADD COLUMN "code" text NOT NULL;--> statement-breakpoint
ALTER TABLE "timeline_thumbnail" ADD COLUMN "session_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "video_clip" ADD COLUMN "session_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "description" ADD CONSTRAINT "description_task_code_id_task_code_task_code_id_fk" FOREIGN KEY ("task_code_id") REFERENCES "public"."task_code"("task_code_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "part_code" ADD CONSTRAINT "part_code_type_id_type_type_id_fk" FOREIGN KEY ("type_id") REFERENCES "public"."type"("type_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "type" ADD CONSTRAINT "type_description_id_description_description_id_fk" FOREIGN KEY ("description_id") REFERENCES "public"."description"("description_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_description_task_code_id" ON "description" USING btree ("task_code_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_description_task_code_label" ON "description" USING btree ("task_code_id","label");--> statement-breakpoint
CREATE INDEX "idx_part_code_type_id" ON "part_code" USING btree ("type_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_part_code_type_code" ON "part_code" USING btree ("type_id","code");--> statement-breakpoint
CREATE INDEX "idx_type_description_id" ON "type" USING btree ("description_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_type_description_code" ON "type" USING btree ("description_id","code");--> statement-breakpoint
ALTER TABLE "recording_ingest" ADD CONSTRAINT "recording_ingest_session_id_session_session_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."session"("session_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_description_id_description_description_id_fk" FOREIGN KEY ("description_id") REFERENCES "public"."description"("description_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_part_code_id_part_code_part_code_id_fk" FOREIGN KEY ("part_code_id") REFERENCES "public"."part_code"("part_code_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "timeline_thumbnail" ADD CONSTRAINT "timeline_thumbnail_session_id_session_session_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."session"("session_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "video_clip" ADD CONSTRAINT "video_clip_session_id_session_session_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."session"("session_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_recording_ingest_open_session" ON "recording_ingest" USING btree ("session_id") WHERE "recording_ingest"."closed_at" IS NULL AND "recording_ingest"."kind" = 'master';--> statement-breakpoint
CREATE INDEX "idx_result_description_id" ON "result" USING btree ("description_id");--> statement-breakpoint
CREATE INDEX "idx_result_part_code_id" ON "result" USING btree ("part_code_id");--> statement-breakpoint
CREATE INDEX "idx_timeline_thumbnail_session_ts" ON "timeline_thumbnail" USING btree ("session_id","timestamp_ms");--> statement-breakpoint
CREATE INDEX "idx_video_clip_session_id" ON "video_clip" USING btree ("session_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_task_group_project_code" ON "task_group" USING btree ("project_id","code");--> statement-breakpoint
ALTER TABLE "recording_ingest" DROP COLUMN "master_video_id";--> statement-breakpoint
ALTER TABLE "result" DROP COLUMN "main_component_id";--> statement-breakpoint
ALTER TABLE "result" DROP COLUMN "component_code_id";--> statement-breakpoint
ALTER TABLE "task_group" DROP COLUMN "group_code";--> statement-breakpoint
ALTER TABLE "timeline_thumbnail" DROP COLUMN "master_video_id";--> statement-breakpoint
ALTER TABLE "video_clip" DROP COLUMN "master_video_id";--> statement-breakpoint
ALTER TABLE "recording_ingest" ADD CONSTRAINT "recording_ingest_kind_target_check" CHECK (("recording_ingest"."kind" = 'master' AND "recording_ingest"."session_id" IS NOT NULL AND "recording_ingest"."clip_id" IS NULL)
       OR ("recording_ingest"."kind" = 'clip' AND "recording_ingest"."clip_id" IS NOT NULL AND "recording_ingest"."session_id" IS NULL));--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_target_check" CHECK (num_nonnulls("result"."description_id", "result"."part_code_id") = 1);--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_layer_check" CHECK ("result"."layer" IS NULL OR "result"."layer" BETWEEN 1 AND 2);