CREATE TABLE "component_code" (
	"component_code_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "component_code_component_code_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"main_component_type_id" integer NOT NULL,
	"code" text NOT NULL,
	"label" text,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "component_type" (
	"component_type_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "component_type_component_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"type_code" text NOT NULL,
	"label" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "inspection_form" (
	"inspection_form_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "inspection_form_inspection_form_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"inspection_type_code" "inspection_type" NOT NULL,
	"version" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "inspection_form_field" (
	"inspection_form_field_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "inspection_form_field_inspection_form_field_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"inspection_form_id" integer NOT NULL,
	"label" text NOT NULL,
	"data_type" text NOT NULL,
	"required" boolean DEFAULT false NOT NULL,
	"is_builtin" boolean DEFAULT false NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "inspection_form_field_data_type_check" CHECK ("inspection_form_field"."data_type" IN ('integer', 'decimal', 'text', 'boolean'))
);
--> statement-breakpoint
CREATE TABLE "main_component" (
	"main_component_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "main_component_main_component_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"task_code_id" integer NOT NULL,
	"description" text NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "main_component_type" (
	"main_component_type_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "main_component_type_main_component_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"main_component_id" integer NOT NULL,
	"component_type_id" integer NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "task_code" (
	"task_code_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "task_code_task_code_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"task_group_id" integer NOT NULL,
	"code" text NOT NULL,
	"label" text NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "task_group" (
	"task_group_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "task_group_task_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"group_code" text NOT NULL,
	"label" text NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "asset" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "component" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "item" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "session_item" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "asset" CASCADE;--> statement-breakpoint
DROP TABLE "component" CASCADE;--> statement-breakpoint
DROP TABLE "item" CASCADE;--> statement-breakpoint
DROP TABLE "session_item" CASCADE;--> statement-breakpoint
DROP INDEX "idx_result_session_item_id";--> statement-breakpoint
DROP INDEX "idx_result_asset_id";--> statement-breakpoint
DROP INDEX "idx_result_component_id";--> statement-breakpoint
DROP INDEX "idx_result_item_id";--> statement-breakpoint
ALTER TABLE "result" ADD COLUMN "main_component_id" integer;--> statement-breakpoint
ALTER TABLE "result" ADD COLUMN "component_code_id" integer;--> statement-breakpoint
ALTER TABLE "result" ADD COLUMN "master_start_ms" bigint;--> statement-breakpoint
ALTER TABLE "result" ADD COLUMN "master_end_ms" bigint;--> statement-breakpoint
ALTER TABLE "result" ADD COLUMN "layer" integer;--> statement-breakpoint
ALTER TABLE "result" ADD COLUMN "custom_values" jsonb;--> statement-breakpoint
ALTER TABLE "result" ADD COLUMN "inspection_form_id" integer;--> statement-breakpoint
ALTER TABLE "component_code" ADD CONSTRAINT "component_code_main_component_type_id_main_component_type_main_component_type_id_fk" FOREIGN KEY ("main_component_type_id") REFERENCES "public"."main_component_type"("main_component_type_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "component_type" ADD CONSTRAINT "component_type_project_id_project_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."project"("project_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inspection_form" ADD CONSTRAINT "inspection_form_project_id_project_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."project"("project_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inspection_form_field" ADD CONSTRAINT "inspection_form_field_inspection_form_id_inspection_form_inspection_form_id_fk" FOREIGN KEY ("inspection_form_id") REFERENCES "public"."inspection_form"("inspection_form_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "main_component" ADD CONSTRAINT "main_component_task_code_id_task_code_task_code_id_fk" FOREIGN KEY ("task_code_id") REFERENCES "public"."task_code"("task_code_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "main_component_type" ADD CONSTRAINT "main_component_type_main_component_id_main_component_main_component_id_fk" FOREIGN KEY ("main_component_id") REFERENCES "public"."main_component"("main_component_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "main_component_type" ADD CONSTRAINT "main_component_type_component_type_id_component_type_component_type_id_fk" FOREIGN KEY ("component_type_id") REFERENCES "public"."component_type"("component_type_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_code" ADD CONSTRAINT "task_code_task_group_id_task_group_task_group_id_fk" FOREIGN KEY ("task_group_id") REFERENCES "public"."task_group"("task_group_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_group" ADD CONSTRAINT "task_group_project_id_project_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."project"("project_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_component_code_main_component_type_id" ON "component_code" USING btree ("main_component_type_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_component_code_branch_code" ON "component_code" USING btree ("main_component_type_id","code");--> statement-breakpoint
CREATE INDEX "idx_component_type_project_id" ON "component_type" USING btree ("project_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_component_type_project_code" ON "component_type" USING btree ("project_id","type_code");--> statement-breakpoint
CREATE INDEX "idx_inspection_form_project_id" ON "inspection_form" USING btree ("project_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_inspection_form_project_type_version" ON "inspection_form" USING btree ("project_id","inspection_type_code","version");--> statement-breakpoint
CREATE INDEX "idx_inspection_form_field_form_id" ON "inspection_form_field" USING btree ("inspection_form_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_inspection_form_field_label" ON "inspection_form_field" USING btree ("inspection_form_id","label");--> statement-breakpoint
CREATE INDEX "idx_main_component_task_code_id" ON "main_component" USING btree ("task_code_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_main_component_task_code_description" ON "main_component" USING btree ("task_code_id","description");--> statement-breakpoint
CREATE INDEX "idx_main_component_type_main_component_id" ON "main_component_type" USING btree ("main_component_id");--> statement-breakpoint
CREATE INDEX "idx_main_component_type_component_type_id" ON "main_component_type" USING btree ("component_type_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_main_component_type_pair" ON "main_component_type" USING btree ("main_component_id","component_type_id");--> statement-breakpoint
CREATE INDEX "idx_task_code_task_group_id" ON "task_code" USING btree ("task_group_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_task_code_group_code" ON "task_code" USING btree ("task_group_id","code");--> statement-breakpoint
CREATE INDEX "idx_task_group_project_id" ON "task_group" USING btree ("project_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_task_group_project_code" ON "task_group" USING btree ("project_id","group_code");--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_main_component_id_main_component_main_component_id_fk" FOREIGN KEY ("main_component_id") REFERENCES "public"."main_component"("main_component_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_component_code_id_component_code_component_code_id_fk" FOREIGN KEY ("component_code_id") REFERENCES "public"."component_code"("component_code_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_inspection_form_id_inspection_form_inspection_form_id_fk" FOREIGN KEY ("inspection_form_id") REFERENCES "public"."inspection_form"("inspection_form_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_result_main_component_id" ON "result" USING btree ("main_component_id");--> statement-breakpoint
CREATE INDEX "idx_result_component_code_id" ON "result" USING btree ("component_code_id");--> statement-breakpoint
CREATE INDEX "idx_result_session_layer" ON "result" USING btree ("session_id","layer");--> statement-breakpoint
ALTER TABLE "result" DROP COLUMN "session_item_id";--> statement-breakpoint
ALTER TABLE "result" DROP COLUMN "asset_id";--> statement-breakpoint
ALTER TABLE "result" DROP COLUMN "component_id";--> statement-breakpoint
ALTER TABLE "result" DROP COLUMN "item_id";--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_target_check" CHECK (num_nonnulls("result"."main_component_id", "result"."component_code_id") = 1);--> statement-breakpoint
ALTER TABLE "result" ADD CONSTRAINT "result_layer_check" CHECK ("result"."layer" IS NULL OR "result"."layer" BETWEEN 1 AND 3);--> statement-breakpoint
DROP TYPE "public"."item_status";